<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="2" tests="3" time="1.6098432540893555">
	<testsuite disabled="0" errors="0" failures="2" name="test" skipped="0" tests="3" time="1.6098432540893555">
		<testcase name="Test1" time="1.602192" classname="test0">
			<failure type="failure" message="This test failed because one of its requirements failed (test.c: 30)">
$1 = {void ()} 0x555555555325 &lt;test0&gt;
</failure>
		</testcase>
		<testcase name="Test2" time="0.004093" classname="test1"/>
		<testcase name="Test3" time="0.003558" classname="test2">
			<failure type="failure" message="Expected 4, received 3 (test.c: 13)">
#0  gunit_hook (expected=..., result=..., line_number=..., file=..., no=...) at ../GUnit.h:13
#1  0x00005555555553ae in test2 () at test.c:13
#2  0x0000555555555300 in gunit_suite (before=..., after=..., tests=..., nr_of_tests=...) at ../GUnit.h:80
#3  0x0000555555555429 in main () at test.c:31
</failure>
		</testcase>
	</testsuite>
</testsuites>
